###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/1

###
GET http://localhost:3000/api/v1/users?search=&page=1&pageSize=5

###
GET http://localhost:3000/api/v1/activities

###
GET http://localhost:3000/api/v1/activities/1

###
# @name login
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
  "email": "trailrunner01@example.com",
  "password": ""
}

###
@token = {{login.response.body.data.token}}

###
GET http://localhost:3000/api/v1/users
Authorization: Bearer {{token}}